services:
  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.21.0@sha256:3d0ac795ff98aa04d1be04311d2dac6c25b4bfc8322dc02e53bc5b170c5018c3
    restart: unless-stopped
    ports:
      - "127.0.0.1:16686:16686"
    networks:
      - synodus-network

  node-exporter:
    extends:
      file: docker-compose.yaml
      service: node-exporter

  prometheus:
    extends:
      file: docker-compose.yaml
      service: prometheus

  grafana:
    extends:
      file: docker-compose.yaml
      service: grafana

  
  envoy:
    image: envoyproxy/envoy:distroless-dev-9c085ba4a27fddea1811a8ecc98fc094dbdd455c
    restart: unless-stopped
    command: ["-c", "/etc/envoy/envoy.yaml"]
    volumes:
      - ./envoy.local.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "127.0.0.1:9901:9901"
      - "10000:10000"
    networks:
      - synodus-network
      - monitoring

networks:
  monitoring:
    driver: bridge
  synodus-network:
    external: true

volumes:
  prometheus_data:
  grafana_data:
