CREATE TABLE orgs (
    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT orgs_pk PRIMARY KEY,

    public_id UUID NOT NULL DEFAULT gen_random_uuid()
        CONSTRAINT orgs_public_id_unique UNIQUE,

    name VARCHAR(255) NOT NULL,

    schema_name VARCHAR(255) NOT NULL
        CONSTRAINT orgs_schema_name_unique UNIQUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    deleted_at TIMESTAMPTZ DEFAULT NULL
);CREATE TABLE users (
    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT users_pk PRIMARY KEY,

    user_id UUID NOT NULL DEFAULT gen_random_uuid()
        CONSTRAINT users_user_id_unique UNIQUE,
    email VARCHAR(255) NOT NULL
        CONSTRAINT users_email_unique UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);CREATE TABLE org_user (
    org_id BIGINT NOT NULL
        CONSTRAINT org_user_org_id_fk REFERENCES orgs (id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL
        CONSTRAINT org_user_user_id_fk REFERENCES users (id) ON DELETE CASCADE);
        -- Canonicalize registry-only names, but refuse to detach an already-created
-- tenant schema from its registry row. Such schemas require operator repair.
DO $$
DECLARE
    organization RECORD;
    canonical_name TEXT;
BEGIN
    FOR organization IN SELECT public_id, schema_name FROM public.orgs LOOP
        canonical_name := 'org_' || replace(organization.public_id::text, '-', '');
        IF organization.schema_name <> canonical_name THEN
            IF to_regnamespace(organization.schema_name) IS NOT NULL THEN
                RAISE EXCEPTION 'organization % has an existing noncanonical tenant schema', organization.public_id
                    USING ERRCODE = 'check_violation';
            END IF;
            UPDATE public.orgs
            SET schema_name = canonical_name
            WHERE public_id = organization.public_id;
        END IF;
    END LOOP;
END $$;

ALTER TABLE public.orgs
    ADD COLUMN lifecycle_state TEXT NOT NULL DEFAULT 'provisioning',
    ADD COLUMN tenant_version BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN tenant_checksum CHAR(64) NOT NULL DEFAULT '',
    ADD COLUMN reconcile_attempts INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ADD COLUMN last_error_code VARCHAR(64),
    ADD COLUMN last_error_detail VARCHAR(512),
    ADD COLUMN last_attempt_at TIMESTAMPTZ,
    ADD COLUMN provisioned_at TIMESTAMPTZ;

UPDATE public.orgs
SET lifecycle_state = CASE WHEN deleted_at IS NULL THEN 'provisioning' ELSE 'deleting' END;

-- These constraints make availability, failure diagnostics, canonical schema
-- ownership, and deletion mutually consistent even outside application code.
ALTER TABLE public.orgs
    ADD CONSTRAINT orgs_lifecycle_state_check
        CHECK (lifecycle_state IN ('provisioning', 'active', 'failed', 'deleting')),
    ADD CONSTRAINT orgs_reconcile_attempts_check
        CHECK (reconcile_attempts >= 0),
    ADD CONSTRAINT orgs_canonical_schema_check
        CHECK (schema_name = 'org_' || replace(public_id::text, '-', '')),
    ADD CONSTRAINT orgs_active_reconciled_check
        CHECK (lifecycle_state <> 'active' OR
            (tenant_version > 0 AND tenant_checksum <> '' AND provisioned_at IS NOT NULL
             AND last_error_code IS NULL AND last_error_detail IS NULL)),
    ADD CONSTRAINT orgs_failed_inspectable_check
        CHECK (lifecycle_state <> 'failed' OR
            (last_error_code IS NOT NULL AND last_error_detail IS NOT NULL AND last_attempt_at IS NOT NULL)),
    ADD CONSTRAINT orgs_deletion_state_check
        CHECK ((deleted_at IS NULL) = (lifecycle_state <> 'deleting'));

-- The provisioner scans only retryable rows ordered by their bounded claim time.
CREATE INDEX orgs_reconciliation_due_idx
    ON public.orgs (next_attempt_at, id)
    WHERE deleted_at IS NULL AND lifecycle_state = 'provisioning';
-- Roles are database-cluster objects, so this migration must initially be run
-- by the existing database administrator. Existing roles are adopted only when
-- their attributes are inside the exact non-privileged allowlist below.
DO $$
DECLARE
    role_record RECORD;
BEGIN
    FOR role_record IN
        SELECT * FROM (VALUES
            ('synodus_owner', false),
            ('synodus_migrator', true),
            ('synodus_provisioner', true),
            ('synodus_runtime', true)
        ) AS desired(role_name, can_login)
    LOOP
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = role_record.role_name) THEN
            IF EXISTS (
                SELECT 1 FROM pg_roles
                WHERE rolname = role_record.role_name
                  AND (rolsuper OR rolcreaterole OR rolcreatedb OR rolreplication OR rolbypassrls)
            ) THEN
                RAISE EXCEPTION 'refusing to adopt privileged database role %', role_record.role_name
                    USING ERRCODE = 'invalid_authorization_specification';
            END IF;
        ELSE
            EXECUTE format('CREATE ROLE %I', role_record.role_name);
        END IF;
    END LOOP;
END $$;

ALTER ROLE synodus_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
ALTER ROLE synodus_migrator LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
ALTER ROLE synodus_provisioner LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
ALTER ROLE synodus_runtime LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;

GRANT synodus_owner TO synodus_migrator WITH INHERIT FALSE, SET TRUE;
GRANT synodus_owner TO synodus_provisioner WITH INHERIT FALSE, SET TRUE;
ALTER ROLE synodus_migrator SET ROLE TO synodus_owner;
ALTER ROLE synodus_provisioner SET ROLE TO synodus_owner;

DO $$
BEGIN
    EXECUTE format('REVOKE ALL ON DATABASE %I FROM synodus_runtime', current_database());
    EXECUTE format('GRANT CONNECT ON DATABASE %I TO synodus_runtime', current_database());
    EXECUTE format('GRANT CONNECT, CREATE, TEMPORARY ON DATABASE %I TO synodus_owner', current_database());
END $$;

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
ALTER SCHEMA public OWNER TO synodus_owner;
GRANT USAGE ON SCHEMA public TO synodus_runtime;

CREATE TABLE IF NOT EXISTS public.schema_migrations (
    version bigint not null primary key,
    dirty boolean not null
);

ALTER TABLE public.orgs OWNER TO synodus_owner;
ALTER TABLE public.users OWNER TO synodus_owner;
ALTER TABLE public.org_user OWNER TO synodus_owner;
ALTER TABLE public.schema_migrations OWNER TO synodus_owner;
ALTER SEQUENCE public.orgs_id_seq OWNER TO synodus_owner;
ALTER SEQUENCE public.users_id_seq OWNER TO synodus_owner;

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM synodus_runtime;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM synodus_runtime;
REVOKE ALL ON public.schema_migrations FROM synodus_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.orgs, public.users, public.org_user TO synodus_runtime;
GRANT USAGE, SELECT ON public.orgs_id_seq, public.users_id_seq TO synodus_runtime;
CREATE OR REPLACE FUNCTION public.canonical_email_display(value TEXT)
RETURNS TEXT
LANGUAGE plpgsql
IMMUTABLE
STRICT
PARALLEL SAFE
AS $$
DECLARE
    normalized TEXT;
    code_point INTEGER;
    position INTEGER;
BEGIN
    normalized := normalize(btrim(value, ' '), NFC);
    IF normalized = '' OR octet_length(normalized) > 254 THEN
        RETURN NULL;
    END IF;

    FOR position IN 1..char_length(normalized) LOOP
        code_point := ascii(substr(normalized, position, 1));
        IF code_point BETWEEN 0 AND 31 OR code_point BETWEEN 127 AND 159 THEN
            RETURN NULL;
        END IF;
    END LOOP;
    RETURN normalized;
END;
$$;

CREATE OR REPLACE FUNCTION public.canonical_email_key(value TEXT)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
STRICT
PARALLEL SAFE
RETURN normalize(
    casefold(public.canonical_email_display(value) COLLATE pg_catalog.pg_unicode_fast),
    NFC
);

ALTER FUNCTION public.canonical_email_display(TEXT) OWNER TO synodus_owner;
ALTER FUNCTION public.canonical_email_key(TEXT) OWNER TO synodus_owner;
REVOKE ALL ON FUNCTION public.canonical_email_display(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_email_key(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.canonical_email_display(TEXT) TO synodus_runtime, synodus_migrator, synodus_provisioner;
GRANT EXECUTE ON FUNCTION public.canonical_email_key(TEXT) TO synodus_runtime, synodus_migrator, synodus_provisioner;

LOCK TABLE public.users IN ACCESS EXCLUSIVE MODE;

DO $$
DECLARE
    invalid_user_ids TEXT;
BEGIN
    SELECT string_agg(user_id::TEXT, ', ' ORDER BY user_id::TEXT)
    INTO invalid_user_ids
    FROM (
        SELECT user_id
        FROM public.users
        WHERE public.canonical_email_key(email) IS NULL
        ORDER BY user_id
        LIMIT 10
    ) AS invalid_users;

    IF invalid_user_ids IS NOT NULL THEN
        RAISE EXCEPTION 'invalid canonical email for user public ids: %', invalid_user_ids
            USING ERRCODE = 'check_violation';
    END IF;
END;
$$;

DO $$
DECLARE
    colliding_user_ids TEXT;
BEGIN
    SELECT string_agg(user_id::TEXT, ', ' ORDER BY user_id::TEXT)
    INTO colliding_user_ids
    FROM (
        SELECT app_user.user_id
        FROM public.users AS app_user
        JOIN (
            SELECT public.canonical_email_key(email) AS email_key
            FROM public.users
            GROUP BY public.canonical_email_key(email)
            HAVING count(*) > 1
        ) AS collision
          ON collision.email_key = public.canonical_email_key(app_user.email)
        ORDER BY app_user.user_id
        LIMIT 10
    ) AS colliding_users;

    IF colliding_user_ids IS NOT NULL THEN
        RAISE EXCEPTION 'canonical email collision for user public ids: %', colliding_user_ids
            USING ERRCODE = 'unique_violation';
    END IF;
END;
$$;

UPDATE public.users
SET email = public.canonical_email_display(email)
WHERE email IS DISTINCT FROM public.canonical_email_display(email);

ALTER TABLE public.users
    DROP CONSTRAINT users_email_unique,
    ADD CONSTRAINT users_email_display_valid CHECK (
        email = public.canonical_email_display(email)
    ),
    ADD COLUMN email_canonical TEXT
        GENERATED ALWAYS AS (public.canonical_email_key(email)) STORED NOT NULL,
    ADD CONSTRAINT users_email_canonical_unique UNIQUE (email_canonical);
ALTER TABLE public.users
    ADD COLUMN password_normalization TEXT;

UPDATE public.users
SET password_normalization = 'legacy_raw'
WHERE password_normalization IS NULL;

ALTER TABLE public.users
    ALTER COLUMN password_normalization SET NOT NULL,
    ALTER COLUMN password_normalization SET DEFAULT 'legacy_raw',
    ADD CONSTRAINT users_password_normalization_closed CHECK (
        password_normalization IN ('legacy_raw', 'nfc_v1')
    );
CREATE TABLE public.sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT sessions_pk PRIMARY KEY,
    session_id UUID NOT NULL DEFAULT gen_random_uuid()
        CONSTRAINT sessions_session_id_unique UNIQUE,
    user_id BIGINT NOT NULL
        CONSTRAINT sessions_user_fk REFERENCES public.users (id) ON DELETE CASCADE,
    token_hash BYTEA NOT NULL
        CONSTRAINT sessions_token_hash_unique UNIQUE,
    user_agent TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    absolute_expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    CONSTRAINT sessions_token_hash_length CHECK (octet_length(token_hash) = 32),
    CONSTRAINT sessions_user_agent_length CHECK (octet_length(user_agent) <= 256),
    CONSTRAINT sessions_time_order CHECK (
        last_seen_at >= created_at AND absolute_expires_at > created_at
    ),
    CONSTRAINT sessions_revoked_after_creation CHECK (
        revoked_at IS NULL OR revoked_at >= created_at
    )
);

CREATE INDEX sessions_user_created_idx
    ON public.sessions (user_id, created_at DESC, id DESC);
CREATE INDEX sessions_revoked_cleanup_idx
    ON public.sessions (revoked_at, id) WHERE revoked_at IS NOT NULL;
CREATE INDEX sessions_absolute_cleanup_idx
    ON public.sessions (absolute_expires_at, id) WHERE revoked_at IS NULL;
CREATE INDEX sessions_idle_cleanup_idx
    ON public.sessions (last_seen_at, id) WHERE revoked_at IS NULL;

ALTER TABLE public.sessions OWNER TO synodus_owner;
ALTER SEQUENCE public.sessions_id_seq OWNER TO synodus_owner;
REVOKE ALL ON public.sessions FROM synodus_runtime;
REVOKE ALL ON public.sessions_id_seq FROM synodus_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.sessions TO synodus_runtime;
GRANT USAGE, SELECT ON public.sessions_id_seq TO synodus_runtime;
LOCK TABLE public.org_user IN ACCESS EXCLUSIVE MODE;

-- Legacy rows carry no distinguishing authorization data. Keep one arbitrary
-- physical row per pair, then grant every surviving membership the same
-- least-privileged role below. No ordering can safely identify an owner.
DELETE FROM public.org_user AS duplicate
USING public.org_user AS retained
WHERE duplicate.org_id = retained.org_id
  AND duplicate.user_id = retained.user_id
  AND duplicate.ctid > retained.ctid;

ALTER TABLE public.org_user
    ADD COLUMN role TEXT NOT NULL DEFAULT 'member',
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ADD CONSTRAINT org_user_role_check
        CHECK (role IN ('owner', 'administrator', 'member')),
    ADD CONSTRAINT org_user_timestamps_check
        CHECK (updated_at >= created_at),
    ADD CONSTRAINT org_user_pk PRIMARY KEY (org_id, user_id);

CREATE INDEX org_user_user_org_idx ON public.org_user (user_id, org_id);
CREATE TABLE public.organization_invitations (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    org_id BIGINT NOT NULL REFERENCES public.orgs(id) ON DELETE CASCADE,
    email_hmac BYTEA NOT NULL CHECK (octet_length(email_hmac) = 32),
    token_hash BYTEA NOT NULL CHECK (octet_length(token_hash) = 32),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT organization_invitations_public_id_unique UNIQUE (public_id),
    CONSTRAINT organization_invitations_org_email_unique UNIQUE (org_id, email_hmac),
    CONSTRAINT organization_invitations_token_hash_unique UNIQUE (token_hash),
    CONSTRAINT organization_invitations_fixed_expiry CHECK (expires_at = created_at + interval '7 days')
);

ALTER TABLE public.organization_invitations OWNER TO synodus_owner;
REVOKE ALL ON public.organization_invitations FROM PUBLIC;
GRANT SELECT, INSERT, DELETE ON public.organization_invitations TO synodus_runtime;
GRANT USAGE, SELECT ON SEQUENCE public.organization_invitations_id_seq TO synodus_runtime;
-- PostgreSQL checks UPDATE privilege for SELECT ... FOR UPDATE even though the
-- invitation application never exposes a general update operation.
GRANT UPDATE ON public.organization_invitations TO synodus_runtime;
CREATE TABLE public.user_public_keys (
    user_id UUID PRIMARY KEY REFERENCES public.users(user_id) ON DELETE CASCADE,
    public_key TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.user_public_keys OWNER TO synodus_owner;
REVOKE ALL ON public.user_public_keys FROM synodus_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_public_keys TO synodus_runtime;
ALTER TABLE public.user_public_keys
    ADD COLUMN encrypted_private_key TEXT,
    ADD COLUMN kek_salt TEXT,
    ADD COLUMN kek_iterations INTEGER,
    ADD COLUMN kek_algorithm VARCHAR(32) NOT NULL DEFAULT 'pbkdf2-sha256',
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

INSERT INTO public.schema_migrations (version, dirty) VALUES (13, false)
ON CONFLICT (version) DO NOTHING;

-- Migration 14: User Device Tokens for Push Notifications
CREATE TABLE IF NOT EXISTS public.user_device_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    token TEXT NOT NULL UNIQUE,
    platform VARCHAR(32) NOT NULL DEFAULT 'android',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_device_tokens_user_id ON public.user_device_tokens (user_id);

ALTER TABLE public.user_device_tokens OWNER TO synodus_owner;
REVOKE ALL ON public.user_device_tokens FROM synodus_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_device_tokens TO synodus_runtime;

INSERT INTO public.schema_migrations (version, dirty) VALUES (14, false)
ON CONFLICT (version) DO NOTHING;

